/// <auto-generated>
/// This code was auto-generated by Dogma for .NET Core on 5/4/2017 21:56:30 UTC. Do not manually edit this file.
/// </auto-generated>
declare module "test-module" {
	export interface TestClass {
		Foo?: string;
		Bar?: boolean;
		Baz?: string[];
	}
}