/// <auto-generated>
/// This code was auto-generated by Dogma for .NET Core on 5/5/2017 01:29:33 UTC. Do not manually edit this file.
/// </auto-generated>
declare module "test-module" {
	export interface TestClass {
		Foo?: string;
		Bar?: boolean;
		Baz?: string[];
		Bat?: number[];
		Collection?: boolean[];
		List?: number[];
		SubBoy?: SubClass;
		Date?: Date;
		DateOffset?: Date;
	}
	export interface SubClass {
		SubFoo?: string;
		SubBar?: boolean;
	}
}